#!/bin/bash

ulimit -Hn 60000
ulimit -Sn 60000

extraContent="* soft nofile 60000
* hard nofile 60000"

if grep -F -q "$extraContent" /etc/security/limits.conf
then
    echo "Content already included"

else
    echo "Content now added"
    echo "$extraContent" >> /etc/security/limits.conf
fi